name: almas_gemelas_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  formz: ^0.7.0
  go_router: ^14.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Light.otf
        - asset: fonts/Satoshi-Regular.otf
        - asset: fonts/Satoshi-Medium.otf
        - asset: fonts/Satoshi-Bold.otf
        - asset: fonts/Satoshi-Black.otf
  assets:
    - .env
    - public/images/
